version: '3'
volumes:
  database:
  payara:
services: 
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=anschluss
      - MYSQL_DATABASE=osterreich
      - MYSQL_USER=alexander
      - MYSQL_PASSWORD=anschluss
    volumes:
      - database:/var/lib/mysql
