version: '2'
volumes:
  database:
  rabbitmq:
  prometheus:
  grafana:
services:
  app:
    build: government-docker
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - "mq"
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=anschluss
      - MYSQL_DATABASE=osterreich
      - MYSQL_USER=alexander
      - MYSQL_PASSWORD=anschluss
    volumes:
      - database:/var/lib/mysql
  mq:
    image: byteflair/rabbitmq-stomp
    ports:
       - "61613:61613"
       - "15672:15672"
       - "5672:5672"
       - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    depends_on:
      - "db"
  prometheus:
    build: prometheus-firehose
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
    depends_on:
      - "app"
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
